FROM node:22-alpine AS build
ARG APP
ARG VITE_BASE=/
ENV VITE_BASE=$VITE_BASE
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/admin-web/package.json apps/admin-web/package.json
COPY apps/customer-web/package.json apps/customer-web/package.json
COPY apps/api/package.json apps/api/package.json
COPY packages/shared-types/package.json packages/shared-types/package.json
COPY packages/pricing-engine/package.json packages/pricing-engine/package.json
COPY packages/connector-sdk/package.json packages/connector-sdk/package.json
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm --filter @movix/${APP} build

FROM nginx:1.27-alpine
COPY infra/nginx/web.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/apps/${APP}/dist /usr/share/nginx/html
